build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'

    nodes:
        php55:
            environment:
                php: 5.5

        php56:
            environment:
                php: 5.6

        php70:
            environment:
                php: 7.0

        php71:
            environment:
                php: 7.1

        php72:
            environment:
                php: 7.2

filter:
    excluded_paths: [tests/*]

tools:
    external_code_coverage:
        timeout: 1800
        runs: 38