language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - ILLUMINATE_VERSION=4.1.*
  - ILLUMINATE_VERSION=4.2.*
  - ILLUMINATE_VERSION=5.0.*
  - ILLUMINATE_VERSION=5.1.*
  - ILLUMINATE_VERSION=5.2.*

matrix:
  include:
    - php: 5.6
      env: ILLUMINATE_VERSION=5.3.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*

before_install:
  - composer self-update
  - if [ "$ILLUMINATE_VERSION" != "" ]; then composer require "illuminate/queue:${ILLUMINATE_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction

script: ./vendor/bin/phpunit